name: CI

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install deps (CI)
        run: npm ci

      # Lint relajado (no bloquea)
      - name: Lint (opcional)
        if: ${{ always() }}
        continue-on-error: true
        run: npm run lint --if-present

      - name: Build
        env:
          NEXT_TELEMETRY_DISABLED: '1'
          CI: '1'
        run: npm run build

